# Generated by Django 5.2.3 on 2025-06-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url_a', models.URLField(blank=True)),
                ('label_a', models.CharField(blank=True, max_length=255)),
                ('video_url_b', models.URLField(blank=True)),
                ('label_b', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_scene_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_from_a', to='ads.scene')),
                ('next_scene_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_from_b', to='ads.scene')),
            ],
        ),
    ]
