# Generated by Django 5.2.3 on 2025-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adconfiguration',
            name='enable_ar_filters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adconfiguration',
            name='include_mini_game',
            field=models.BooleanField(default=False),
        ),
    ]
