# Generated by Django 5.2.4 on 2025-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_remove_ad_id_from_scene"),
    ]

    operations = [
        migrations.AddField(
            model_name="adconfiguration",
            name="edges",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adconfiguration",
            name="nodes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
