# Generated by Django 5.2.3 on 2025-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_adconfiguration_edges_adconfiguration_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adconfiguration',
            name='edges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='adconfiguration',
            name='nodes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
