# Generated by Django 5.2.3 on 2025-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_adconfiguration_edges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adconfiguration',
            name='template_type',
            field=models.CharField(default='aige', max_length=50),
        ),
    ]
