// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wadifwqpmmhftspjjxiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhZGlmd3FwbW1oZnRzcGpqeGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODA0MTAsImV4cCI6MjA2NTU1NjQxMH0.ASAhaGO-sKSiXu4av5RNQokDZyu7GpuR__vy5VtH3S4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);